### ISSUE TITLE
Marking the repositories with a label

### ISSUE THREAD

**Issue by PepikVaio** [kg4zow/rm2-scripts#2]
Give this repository a label.
It's easier for people to find.

**Comment by kg4zow** [comment]
No idea what you're talking about. Are you *asking* me to do something, or are you saying you *did* something?

**Comment by PepikVaio** [comment]
Wrong translation, sorry.

Give this repository a label.
It's easier for people to find.

**Comment by kg4zow** [comment]
Saying the exact same thing multiple times doesn't make it any clear, sorry.

**Comment by kg4zow** [comment]
Actually, after reading [this "issue"](https://github.com/kg4zow/rm2-scripts/issues/3), I did some reading in Github's documentation.

* **Labels** are metadata tags which can be applied to *issues and pull requests*. Each repo has a set of possible label names, and people who open issues or pull requests can use these labels to categorize them.

    I tried using them once, and I found that unless the repo has dozens of issues or PRs, they're more trouble than they're worth.

* **Topics** are metadata tags that can be applied to *repos*, which are supposed to make them "easier to find". Apparently some people search for repos by "topic", I don't know.

    I just added the `remarkable-tablet` "topic" to this repo, for that other issue.

If neither of these are what you're trying to ask about, please try again ... and this time **explain it in more detail**.

**Comment by kg4zow** [comment]
I ... *guess* this is done? If not, let me know.
