### ISSUE TITLE
Add remarkable-tablet topic

### ISSUE THREAD

**Issue by Eeems** [kg4zow/rm2-scripts#3]
Could you add the remarkable-tablet topic?
https://remarkable.guide/devel/github.html#remarkable-tablet-topic

**Comment by kg4zow** [comment]
I didn't know that Github even *had* a "topics" functionality. I use Github all day long at `$DAYJOB`, but we have an enterprise account with several "organizations" under it. All of our repos are "internal", and I always know which repo I'm looking for, I've never needed to make a repo "easier to find" like that.

Actually, now I'm wondering if this is something we *could* use internally. (I'm also wondering when I'll have *time* to think about this, but that's a different discussion.)

Thanks for pointing this out.

Also, now I'm wondering if maybe this is what the guy who opened [that other "issue"](https://github.com/kg4zow/rm2-scripts/issues/2) was talking about ...
